[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
demo = "FsBzY1Qp6PUdbef3bN6rqL1JVQy5Ss8zZqUxPkgNq32K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=f251df6c-7f51-4b1c-9394-92daafd620ee"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
